name: GitHub Actions Intune Cleanup
on: workflow_dispatch
jobs: 
  cleanup:
    permissions:
      id-token: write 
      contents: read

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: Get Graph Credentials
      shell: pwsh
      run: |
        $GraphTokenResponse = az account get-access-token --resource https://graph.microsoft.com
        $GraphToken = ($GraphTokenResponse | ConvertFrom-Json).accessToken
        Add-Content -Path $env:GITHUB_ENV -Value "GRAPH_TOKEN=$GraphToken"
   
    - name: Delete Intune Managed Device
      shell: pwsh
      run: |
        .\delete-intune-managed.ps1 -GraphToken $env:GRAPH_TOKEN -DeviceName UK-AWS-94751646 -UPN Craig@murphycraig250gmailcom.onmicrosoft.com
    
    - name: Delete Intune Autopilot Device
      shell: pwsh
      run: |
        .\delete-intune-autopilot.ps1 -GraphToken $env:GRAPH_TOKEN -DeviceName UK-AWS-94751646 -Manufacturer 1400
